# Generated by Django 5.0.4 on 2024-05-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', models.DateField()),
                ('department_location', models.CharField(max_length=100)),
                ('person_making_request', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('category_of_request', models.CharField(choices=[('Carpentry', 'Carpentry'), ('Electrical', 'Electrical'), ('Air-condition', 'Air-condition'), ('Plumbing', 'Plumbing'), ('Other', 'Other')], max_length=100)),
                ('description_of_request', models.TextField()),
                ('check_repaired_by', models.CharField(max_length=100)),
                ('date_of_completion', models.DateField(blank=True, null=True)),
                ('approval_by_property', models.BooleanField(default=False)),
                ('solved', models.BooleanField(default=False)),
            ],
        ),
    ]
