# Generated by Django 5.0.4 on 2024-05-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINTENANCE', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='solved',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='process',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved'), ('unsolved', 'Unsolved'), ('insoluble', 'Insoluble')], default='pending', max_length=10),
        ),
    ]
